# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Collector < Formula
  desc "Package generator for RocketBlend."
  homepage "https://docs.rocketblend.io/v/collector/"
  version "1.5.0"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rocketblend/rocketblend-collector/releases/download/v1.5.0/collector_Darwin_arm64.tar.gz"
      sha256 "1383c8168c37da39dec822ee0ac753fafcf14af23010c678fd14ad2543b347d6"

      def install
        bin.install "collector"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rocketblend/rocketblend-collector/releases/download/v1.5.0/collector_Darwin_x86_64.tar.gz"
      sha256 "c0468d2a66096e1ea6604addfb60e88ebbdcafe6c69d760c48a90e9b25d01f72"

      def install
        bin.install "collector"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rocketblend/rocketblend-collector/releases/download/v1.5.0/collector_Linux_arm64.tar.gz"
      sha256 "adc245cf0f1d9e9e5e8b1ed992cdc22ff3246065267133e78fd6483b780fa873"

      def install
        bin.install "collector"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rocketblend/rocketblend-collector/releases/download/v1.5.0/collector_Linux_x86_64.tar.gz"
      sha256 "294b1f5b93c4c726f4a61569f18061b3a5352e753dc6fe84cb1dc425ae13bdbf"

      def install
        bin.install "collector"
      end
    end
  end
end
